/* 
 * AdventureWorks.EmployeeManager.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using AdventureWorks.EmployeeManager.Client;
using AdventureWorks.EmployeeManager.Api;

namespace AdventureWorks.EmployeeManager.Test
{
    /// <summary>
    ///  Class for testing ValuesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ValuesApiTests
    {
        private ValuesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ValuesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValuesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ValuesApi
            //Assert.IsInstanceOfType(typeof(ValuesApi), instance, "instance is a ValuesApi");
        }

        
        /// <summary>
        /// Test ValuesDelete
        /// </summary>
        [Test]
        public void ValuesDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ValuesDelete(id);
            
        }
        
        /// <summary>
        /// Test ValuesGet
        /// </summary>
        [Test]
        public void ValuesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ValuesGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test ValuesGet_0
        /// </summary>
        [Test]
        public void ValuesGet_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ValuesGet_0(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test ValuesPost
        /// </summary>
        [Test]
        public void ValuesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //instance.ValuesPost(value);
            
        }
        
        /// <summary>
        /// Test ValuesPut
        /// </summary>
        [Test]
        public void ValuesPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string value = null;
            //instance.ValuesPut(id, value);
            
        }
        
    }

}
